language: node_js
node_js:
  - "11"
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls