export const CREATE_AUTHOR_SUCCESS = "CREATE_AUTHOR_SUCCESS";
export const DELETE_AUTHOR_SUCCESS = "DELETE_AUTHOR_SUCCESS";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
export const UPDATE_AUTHOR_SUCCESS = 'UPDATE_AUTHOR_SUCCESS';
export const GET_NUMBER_OF_AUTHORS_SUCCESS = 'GET_NUMBER_OF_AUTHORS_SUCCESS';
export const UPDATE_NUMBER_OF_AUTHORS_SUCCESS = 'UPDATE_NUMBER_OF_AUTHORS_SUCCESS';
