export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const GET_NUMBER_OF_COURSES_SUCCESS = 'GET_NUMBER_OF_COURSES_SUCCESS';
export const UPDATE_NUMBER_OF_COURSES_SUCCESS = 'UPDATE_NUMBER_OF_COURSES_SUCCESS';